from pathlib import Path

from basic_web_backend.application import WebApplication
from basic_web_backend.config import ApplicationConfig
from basic_web_backend.response import html_response, json_response

from basic_web_server.server import Server as LemaServer

EXAMPLE_FOLDER = Path(__file__).parent
STATIC_FOLDER = EXAMPLE_FOLDER / "static"


config = ApplicationConfig(
    static_folder=STATIC_FOLDER,
    static_url_path="/static",
)

app = WebApplication(config=config)

@app.route(path="/")
def index(request):
    return html_response(
               """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            >

            <title>Basic Web Backend</title>

            <link
                rel="stylesheet"
                href="/static/css/style.css"
            >

            <script
                src="/static/js/app.js"
                defer
            ></script>
        </head>

        <body>
            <main class="container">
                <h1>Basic Web Backend</h1>

                <p>
                    This HTML was generated by a
                    backend view.
                </p>

                <form id="message-form">
                    <label for="name">
                        Name:
                    </label>

                    <input
                        id="name"
                        name="name"
                        value="Martin"
                        required
                    >

                    <button type="submit">
                        Send JSON request
                    </button>
                </form>

                <p id="message">
                    No message received yet.
                </p>
        </body>
        </html>
        """
    )

@app.route(path="/api/message", methods=["POST"])
def api_message(request):
    data = request.get_json()
    name = data.get("name")

    return json_response(
        data={"message": f"Hello, {name}! Your JSON request was processed."}

    )

server = LemaServer(application=app)
server.start_console()